In [2]:
import pandas as pd
import numpy as np

#%% sort in descending order ad ascending order


idx=[ 'D','A','B','C']
contr=[6700,8000,5400,3400]
s12=pd.Series(contr, idx)
# i)
# s12.sort_values(ascending=False, inplace=True)

# print(s12)
#%%
#ii)
s12.sort_index(inplace=True)
print(s12)

A    8000
B    5400
C    3400
D    6700
dtype: int64

In [3]:
# list of strings
lst = ['Geeks', 'For', 'Geeks', 'is', 
            'portal', 'for', 'Geeks']

In [4]:
# Calling DataFrame constructor on list
df = pd.DataFrame(lst, columns = ["Words"])
# print(df)
df["Words"]

0     Geeks
1       For
2     Geeks
3        is
4    portal
5       for
6     Geeks
Name: Words, dtype: object

In [5]:
df=pd.DataFrame(lst,columns=['Data'])
df

     Data
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [6]:
# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [7]:
#%%
# Define a dictionary containing employee data
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', np.nan, 'Kannauj'],
        'Qualification':[np.nan, 'MA', 'MCA', 'Phd']}
 
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data)
df

     Name  Age  Address Qualification
0     Jai   27    Delhi           NaN
1  Princi   24   Kanpur            MA
2  Gaurav   22      NaN           MCA
3    Anuj   32  Kannauj           Phd

In [8]:
# select two columns
print(df[['Name', 'Qualification']])

     Name Qualification
0     Jai           NaN
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd

In [9]:
# using isnull() function  
np.sum(df.isnull())
#%%
# df.notnull()

d:\Users\bsit22f.0007\AppData\Local\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

Name             0
Age              0
Address          1
Qualification    1
dtype: int64

In [10]:
df.fillna(0, inplace=True)
df.dropna(inplace=True)

In [11]:
for i, j in df.iterrows():
    print(i)
    print(j)
#%%
for i in df.columns:
    print(i)
    print(df[i])

#%%
df.index = ['x', 'y', 'z', 'f']

0
Name               Jai
Age                 27
Address          Delhi
Qualification        0
Name: 0, dtype: object
1
Name             Princi
Age                  24
Address          Kanpur
Qualification        MA
Name: 1, dtype: object
2
Name             Gaurav
Age                  22
Address               0
Qualification       MCA
Name: 2, dtype: object
3
Name                Anuj
Age                   32
Address          Kannauj
Qualification        Phd
Name: 3, dtype: object
Name
0       Jai
1    Princi
2    Gaurav
3      Anuj
Name: Name, dtype: object
Age
0    27
1    24
2    22
3    32
Name: Age, dtype: int64
Address
0      Delhi
1     Kanpur
2          0
3    Kannauj
Name: Address, dtype: object
Qualification
0      0
1     MA
2    MCA
3    Phd
Name: Qualification, dtype: object

In [12]:
# Define a dictionary containing employee data
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', np.nan, 'Kannauj'],
        'Qualification':[np.nan, 'MA', 'MCA', 'Phd']}

In [20]:
df=pd.DataFrame(data)

In [19]:
avg=sum(df['Age'])/len(df['Age'])
avg

26.25

In [22]:
# df.groupby('Name')['Age'].mean()
df.groupby('Name').agg({'Age':'mean'})

         Age
Name
Anuj    32.0
Gaurav  22.0
Jai     27.0
Princi  24.0

In [ ]:
# df['Age']>avg
# df[df['Age']>avg]

0     True
1    False
2    False
3     True
Name: Age, dtype: bool

In [13]:
df = pd.read_csv("user_behavior_dataset.csv")  

df["Device Model"][0] = np.nan

df.loc[0, "Screen On Time (hours/day)"] = np.nan

df.fillna(0, inplace=True)

FileNotFoundError: [Errno 2] No such file or directory: 'user_behavior_dataset.csv'

In [ ]:
DM_unique = df['Device Model'].unique()

df['Device Model'].value_counts() / len(df)
df['Device Model'].nunique()

df = df.drop([0,1,2]).reset_index()

In [ ]:
df.drop(["Device Model", "Operating System"], axis=1, inplace = True)

In [ ]:
df = pd.DataFrame({ 
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie'], 
    'Age': [25, 32, 25, 37] 
}) 

df.duplicated()
#%%
duplicates = df[df.duplicated()] 
print(duplicates)
#%%
df.drop_duplicates()
#%%
df.drop_duplicates(inplace=True, ignore_index=True)

In [ ]:
df = pd.read_csv("user_behavior_dataset.csv") 

df.sort_values("App Usage Time (min/day)", inplace=True, ignore_index=True)
filter = df["Operating System"] == "Android"
df.where(filter, inplace=True)

In [ ]:
df["Operating System"] == "Android" 

android_df = df[ df["Operating System"] == "Android" ]
#%%
filter1 = df["Operating System"] == "Android"

# making boolean series for age
filter2 = df["Age"] > 24
# filtering data on basis of both filters
#df.where(filter1 & filter2, inplace=True)

df_new = df[ (df["Operating System"] == "Android") & (df["Age"] > 24) ]